# Generated by Django 3.0.2 on 2020-10-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201028_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='landing_page',
            field=models.ImageField(upload_to='landing_pages'),
        ),
    ]
